### ISSUE TITLE
Checkly Kubernetes Integration

### ISSUE THREAD

**Issue by dirien** [checkly/public-roadmap#119]
It would be nice to have an Checkly Kubernetes Operator, where i could just annotate my ingress ressource with checkly specific informations. 

Like 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    checklyhq.com/assertion-target: 200
    checklyhq.com/assertion-comparison: EQUAL
    checklyhq.com/locations-eu-west: true
spec:
  rules:
  - http:
      ...
```

So any exposed endpoint gets automatically add to checkly and the  perform the checks. 

More fancy checks could be also part of a configmap for the operator...
